---
title: "Dissertation"
subtitle: "Alignment as a Contextual Property: Experimental Evidence of Oversight-Conditioned Deception"
author: 
  - "Jayrup D Nakawala"
  - "u2613621"
#   - "Dr. Aloysius Adotey Edoh"
format: 
  revealjs:
    theme: moon
---


:::{.center}
## Alignment $\neq$ Internalized Ethics



:::

## Why is this a computing problem?

- explain why

## Literature Review findings

- how others have approached this, or related problem in the past?
- what lessons can be learned from them?
- convince the assessors that you have gained some knowledge about the background of the problem
- cite information/sources (references, at the end of the presentation)

## What is my proposed solution?

- how will i solve the problem listed previously
- give a design overview of the structure of the solution

## How will i evaluate the solution?

- state the evaluation/validation method and how this method has been used before
- why this method and not another
- what are the benefits and risks of this method


## Project planning and Methodology

- my progress to date
- project plan with achieved and future milestones
- Gantt chart
- project methodology and method of application

## References



